export const DOCUMENT_LABELS = {
  actions: {
    upload: 'Enviar',
    uploadDocument: 'Enviar documento',
    download: 'Descarregar',
    downloadFolder: 'Descarregar pasta',
    open: 'Abrir',
    select: 'Seleccionar',
    deselect: 'Desseleccionar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    replace: 'Substituir',
    changeType: 'Alterar tipo',
    save: 'Guardar',
    close: 'Fechar',
    newType: 'Novo tipo',
    customType: 'Tipo personalizado',
  },
  emptyStates: {
    noDocuments: 'Ainda não existem documentos.',
    noDocumentsInFolder: 'Esta pasta está vazia.',
    noResults: 'Nenhum resultado encontrado.',
  },
  toasts: {
    preparingZip: 'A preparar ZIP...',
    zipReady: 'Descarregado',
    zipError: 'Erro ao preparar ZIP',
    zipPartial: (errors: number) => `Descarregado com ${errors} erro(s)`,
    tooLarge: (mb: number) =>
      `Selecção demasiado grande (${mb} MB). Divide em lotes menores.`,
    uploading: (current: number, total: number) =>
      `A enviar ${current}/${total} ficheiros...`,
    uploaded: 'Documentos enviados com sucesso',
    uploadError: 'Erro ao enviar documentos',
    deleted: 'Documento eliminado',
    deleteError: 'Erro ao eliminar documento',
    fileRejected: (name: string) => `${name}: extensão não permitida`,
    fileTooLarge: (name: string) => `${name}: excede o limite de 50 MB`,
    typeCreated: 'Tipo criado com sucesso',
    typeCreateError: 'Erro ao criar tipo',
  },
  labels: {
    selected: (n: number) => `${n} ${n === 1 ? 'pasta seleccionada' : 'pastas seleccionadas'}`,
    filesCount: (n: number) => `${n} ${n === 1 ? 'ficheiro' : 'ficheiros'}`,
    fileOfTotal: (current: number, total: number) => `${current} / ${total}`,
    expiresOn: 'Validade',
    expiryOptional: 'Data de validade (opcional)',
    expiryRequired: 'Data de validade',
    hasExpiry: 'Tem validade?',
    notes: 'Notas',
    fileLabel: 'Etiqueta',
    fileLabelPlaceholder: 'Ex: Frente, Verso, Cópia...',
    uploadDrag: 'Arraste ficheiros para aqui ou clique para seleccionar',
    uploadAccepted: 'Aceita: PDF, JPG, PNG, DOC, DOCX (máx. 50 MB)',
    docType: 'Tipo de documento',
    docTypeName: 'Nome do tipo',
    noMimePreview: 'Pré-visualização não disponível',
    confirmDelete: 'Tem a certeza de que pretende eliminar este documento? Esta acção é irreversível.',
  },
  errors: {
    loadFailed: 'Erro ao carregar documentos.',
  },
} as const

export type DocumentLabels = typeof DOCUMENT_LABELS
