export const DOCUMENT_LABELS = {
  actions: {
    upload: 'Enviar',
    uploadDocument: 'Enviar documento',
    download: 'Descarregar',
    downloadFolder: 'Descarregar pasta',
    open: 'Abrir',
    select: 'Seleccionar',
    deselect: 'Desseleccionar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    replace: 'Substituir',
    changeType: 'Alterar tipo',
    save: 'Guardar',
    close: 'Fechar',
    newType: 'Novo tipo',
    customType: 'Tipo personalizado',
    send: 'Enviar',
    retry: 'Tentar novamente',
  },
  send: {
    title: 'Enviar documentos',
    channelEmail: 'Email',
    channelWhatsapp: 'WhatsApp',
    senderEmailLabel: 'Enviar de',
    senderWhatsappLabel: 'Instância WhatsApp',
    senderPickEmail: 'Selecciona a conta de email',
    senderPickWhatsapp: 'Selecciona a instância',
    noEmailAccounts: 'Não tens contas de email configuradas',
    noWhatsappInstances: 'Não tens instâncias de WhatsApp configuradas',
    configureEmail: 'Configurar email',
    configureWhatsapp: 'Configurar WhatsApp',
    recipientsTitle: 'Destinatários',
    addAdhocEmail: 'Adicionar email...',
    addAdhocPhone: 'Adicionar telefone (+351 ...)',
    subject: 'Assunto',
    emailBody: 'Mensagem',
    whatsappMessage: 'Mensagem (opcional)',
    attachmentsSummary: (count: number, mb: number) =>
      `${count} ${count === 1 ? 'ficheiro' : 'ficheiros'} · ${mb} MB`,
    attachmentsTooLarge:
      'Anexos excedem 25 MB — envio pode falhar no servidor SMTP',
    noChannelSelected: 'Nenhum canal seleccionado',
    noRecipients: 'Selecciona pelo menos um destinatário',
    noFiles: 'Selecção sem ficheiros',
    consultantLabel: 'Consultor',
    ownerLabel: 'Proprietário',
    ownerMainLabel: 'Proprietário (principal)',
    adhocLabel: 'Outro',
    noPhoneTooltip: 'Sem telefone registado',
    noEmailTooltip: 'Sem email registado',
    invalidEmail: 'Email inválido',
    invalidPhone: 'Telefone inválido',
    statusPending: 'Em espera',
    statusSending: 'A enviar...',
    statusSuccess: 'Enviado',
    statusFailed: 'Falhou',
    sending: 'A enviar...',
    allSent: 'Todos os envios concluídos',
    partialFailed: (n: number) =>
      `${n} ${n === 1 ? 'envio falhou' : 'envios falharam'}`,
  },
  emptyStates: {
    noDocuments: 'Ainda não existem documentos.',
    noDocumentsInFolder: 'Esta pasta está vazia.',
    noResults: 'Nenhum resultado encontrado.',
  },
  toasts: {
    preparingZip: 'A preparar ZIP...',
    zipReady: 'Descarregado',
    zipError: 'Erro ao preparar ZIP',
    zipPartial: (errors: number) => `Descarregado com ${errors} erro(s)`,
    tooLarge: (mb: number) =>
      `Selecção demasiado grande (${mb} MB). Divide em lotes menores.`,
    uploading: (current: number, total: number) =>
      `A enviar ${current}/${total} ficheiros...`,
    uploaded: 'Documentos enviados com sucesso',
    uploadError: 'Erro ao enviar documentos',
    deleted: 'Documento eliminado',
    deleteError: 'Erro ao eliminar documento',
    fileRejected: (name: string) => `${name}: extensão não permitida`,
    fileTooLarge: (name: string) => `${name}: excede o limite de 50 MB`,
    typeCreated: 'Tipo criado com sucesso',
    typeCreateError: 'Erro ao criar tipo',
  },
  labels: {
    selected: (n: number) => `${n} ${n === 1 ? 'pasta seleccionada' : 'pastas seleccionadas'}`,
    filesCount: (n: number) => `${n} ${n === 1 ? 'ficheiro' : 'ficheiros'}`,
    fileOfTotal: (current: number, total: number) => `${current} / ${total}`,
    expiresOn: 'Validade',
    expiryOptional: 'Data de validade (opcional)',
    expiryRequired: 'Data de validade',
    hasExpiry: 'Tem validade?',
    notes: 'Notas',
    fileLabel: 'Etiqueta',
    fileLabelPlaceholder: 'Ex: Frente, Verso, Cópia...',
    uploadDrag: 'Arraste ficheiros para aqui ou clique para seleccionar',
    uploadAccepted: 'Aceita: PDF, JPG, PNG, DOC, DOCX (máx. 50 MB)',
    docType: 'Tipo de documento',
    docTypeName: 'Nome do tipo',
    noMimePreview: 'Pré-visualização não disponível',
    confirmDelete: 'Tem a certeza de que pretende eliminar este documento? Esta acção é irreversível.',
  },
  errors: {
    loadFailed: 'Erro ao carregar documentos.',
  },
} as const

export type DocumentLabels = typeof DOCUMENT_LABELS
