-- ─────────────────────────────────────────────────────────────────────────
-- 20260531: Lead observations (timestamped) + AI client profile cache
--
-- Splits the historical `lead.observacoes` single-textarea into a stream of
-- dated observations stored in `leads_activities`. Each observation gets:
--   - `occurred_at` — when it actually happened (editable by the consultant,
--     defaults to creation time). Distinct from `created_at` which is the
--     immutable "when did it land in the system" timestamp for audit.
--   - `is_pinned` — surface critical observations to the top regardless of
--     date ordering ("bebé a chegar", "preferia R/C", etc.).
--
-- AI client profile cache lives on `leads` itself (not a side table) to keep
-- the read path single-row. Nullable fields — `null` means "never generated".
--
-- All additive. Zero data destruction. Revert at the bottom of file.
-- ─────────────────────────────────────────────────────────────────────────

-- 1. Activities — occurred_at + is_pinned -----------------------------------
ALTER TABLE leads_activities
  ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN leads_activities.occurred_at IS
  'When the activity actually happened. NULL = use created_at. Editable by consultant.';
COMMENT ON COLUMN leads_activities.is_pinned IS
  'Pinned observations surface to the top of the contact timeline.';

-- Functional index for fast timeline queries ordered by effective date
CREATE INDEX IF NOT EXISTS idx_leads_activities_contact_effective_date
  ON leads_activities (contact_id, COALESCE(occurred_at, created_at) DESC);

-- 2. Leads — AI client profile cache ----------------------------------------
ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS ai_profile JSONB,
  ADD COLUMN IF NOT EXISTS ai_profile_summary_md TEXT,
  ADD COLUMN IF NOT EXISTS ai_profile_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ai_profile_generated_by UUID REFERENCES dev_users(id);

COMMENT ON COLUMN leads.ai_profile IS
  'Structured persona generated by GPT from activities + entries + negocios. Shape: {summary, traits, preferences, concerns, opportunities}.';
COMMENT ON COLUMN leads.ai_profile_summary_md IS
  'Short markdown summary of the profile, suitable for quick-glance display.';
COMMENT ON COLUMN leads.ai_profile_generated_at IS
  'Last time the profile was regenerated. NULL = never generated.';

-- ─────────────────────────────────────────────────────────────────────────
-- Revert (manual rollback):
--
-- ALTER TABLE leads
--   DROP COLUMN IF EXISTS ai_profile_generated_by,
--   DROP COLUMN IF EXISTS ai_profile_generated_at,
--   DROP COLUMN IF EXISTS ai_profile_summary_md,
--   DROP COLUMN IF EXISTS ai_profile;
--
-- DROP INDEX IF EXISTS idx_leads_activities_contact_effective_date;
--
-- ALTER TABLE leads_activities
--   DROP COLUMN IF EXISTS is_pinned,
--   DROP COLUMN IF EXISTS occurred_at;
-- ─────────────────────────────────────────────────────────────────────────
