ALTER TABLE temp_partners
  ADD COLUMN IF NOT EXISTS cover_image_url TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT;

COMMENT ON COLUMN temp_partners.cover_image_url IS 'Hero/cover image shown at the top of the partner detail sheet. Uploaded to R2 or generated by AI.';
COMMENT ON COLUMN temp_partners.description IS 'Rich description shown on the partner detail page. Can be improved or generated via AI.';
